<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Multiple Modules</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container-fluid">
    <?php echo $this->getContent(); 
   ?>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="<?php URL_ROOT?>/public/assets/script.js" type="text/javascript"></script>
</body>
</html>