<?php
    if(isset($token))
    {
        echo '<div class="alert alert-success" role="alert">
        Token:'.$token.'
      </div>';
    }

?>
<div class="container">
        <div class="row align-items-center g-lg-5 py-5">
            <div class="col-md-10 mx-auto col-lg-5">
                <!--Start of form tag-->
                <?php 
                        echo Phalcon\Tag::form(
                        [
                            BASE_URI."/login/signup",
                            "method" => "post",
                            'class' =>"p-4 p-md-5 border rounded-3 bg-light"
                        ]
                    );
                ?>
                    <h1 class="text-center text-primary">Sign Up</h1>

                    <!--Taking Full name as input by user-->
                    <div class="form-floating mb-3">
                        <label for="floatingInput">Full Name</label>
                        <?php
                            echo Phalcon\Tag::textField(
                                [
                                    'name' => 'fullname',
                                    'class' => 'form-control',
                                    'id' => 'floatingInput',
                                    'required' => true,
                                    'placeholder' => 'Full Name'
                                ]
                            )
                        ?>
                    </div>


                    <!--Taking email as input by user-->
                    <div class="form-floating mb-3">
                        <label for="floatingInput">Email address</label>
                        <?php echo Phalcon\Tag:: emailField(
                            [
                                'name' => 'email',
                                'class' => 'form-control',
                                'id' => 'floatingInput',
                                'required' => true,
                                'placeholder' => 'name@example.com'
                            ]
                            );?>
                    </div>


                    <!--Taking password as input by user-->
                    <div class="form-floating mb-3">
                        <label for="floatingInput">Password</label>
                        <?php echo Phalcon\Tag:: passwordField(
                            [
                                'name' => 'password',
                                'class' => 'form-control',
                                'id' => 'floatingInput',
                                'required' => true,
                                'placeholder' => 'password'
                            ]
                            );?>
                    </div>

                    <!--Submitting the data to fetch the users detail-->
                    <?php
                        echo Phalcon\Tag::submitButton(
                            [
                                "Sign Up",
                                'class' => 'w-100 btn btn-lg btn-primary'
                            ]
                        );
                    ?>
                    <hr class="my-4">
                    <a href='<?php echo BASE_URI;?>/login/index' class="text-primary d-block text-center">Click to Login</a>
                    <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
                </form>
                <!--End of form tag-->
              
            </div>
        </div>
    </div>