<?php

echo '<h1>Application Order Details</h1>';
echo '<table class="table" id="order">
              <tr class="text-center">
                  <th>Sr No.</th>
                  <th>Customer Email</th>
                  <th>Customer Name</th>
                  <th>Product Name</th>
                  <th>Product Quantity</th>
                  <th>Status</th>
                  <th></th>
              </tr>';
              $serialNumber=1;
  foreach($orderDetail as $value) 
  {
    // print_r($value['_id']['$oid']);
    // die;
      echo '<tr class="text-center">
              <td>'.$serialNumber.'</td>
              <td>'.$value['c_email'].'</td>
              <td>'.$value['name'].'</td>
              <td>'.$value['pname'].'</td>
              <td>'.$value['quantity'].'</td>
              <td id="status">'.$value['status'].'</td>
              <td> 
                  <select class="status" id="'.$value['_id']['$oid'].'">
                      <option value="Paid">Paid</option>
                      <option value="Processing">Processing</option>
                      <option value="Dispatched">Dispatched</option>
                      <option value="Shipped">Shipped</option>
                      <option value="Refunded">Refunded</option>
                  </select>
                  <button id="'.$value['_id']['$oid'].'" class="changeStatus">Change Status</button>
              </td>';
            
              $serialNumber++;
  }
  echo '</table>';
  
  